// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class Action {

	public static final String BUILD_SETTLEMENT = "BUILD_SETTLEMENT";
	public static final String BUILD_CITY = "BUILD_CITY";
	public static final String BUILD_ROAD = "BUILD_ROAD";
	public static final String PASS = "PASS";

	/**
	 *
	 */
	private int roundNumber;
	/**
	 *
	 */
	private int playerId;
	/**
	 *
	 */
	private String description;

	/**
	 *
	 * @param roundNumber
	 * @param playerId
	 * @param description
	 */
	public Action(int roundNumber, int playerId, String description) {
		this.roundNumber = roundNumber;
		this.playerId = playerId;
		this.description = description;
	}

	/**
	 * 
	 * @return the action description (e.g. BUILD_SETTLEMENT, PASS)
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * 
	 * @return
	 */
	public String toString() {
		return "[" + roundNumber + "] / [" + playerId + "]: " + description;
	}
}