// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.List;
import java.util.Random;

/************************************************************/
/**
 * 
 */
public class Agent {
	/**
	 * 
	 */
	private Player player;
	/**
	 * 
	 */
	private Random random;

	/**
	 * 
	 * @param player 
	 */
	public Agent(Player player) {
		this.player = player;
		this.random = new Random();
	}

	/**
	 * 
	 * @return 
	 */
	public Action makeDecision() {
		// To be implemented
		return null;
	}

	/**
	 * 
	 * @return 
	 */
	public int rollDice() {
		return (random.nextInt(6) + 1) + (random.nextInt(6) + 1);
	}

	/**
	 * 
	 * @param availableActions 
	 * @return 
	 */
	public Action chooseRandomAction(List<Action> availableActions) {
		if (availableActions == null || availableActions.isEmpty()) {
			return null;
		}
		return availableActions.get(random.nextInt(availableActions.size()));
	}

	/**
	 * 
	 * @param board 
	 * @param resourceBank 
	 * @return 
	 */
	public void takeTurn(Board board, ResourceBank resourceBank) {
		// To be implemented
	}

	/**
	 * 
	 * @return 
	 */
	public Player getPlayer() {
		return player;
	}
}