// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.List;
import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private List<Tile> tiles;
	/**
	 * 
	 */
	private List<Node> nodes;
	/**
	 * 
	 */
	private List<Edge> edges;

	/**
	 * 
	 * @param tiles 
	 * @param nodes 
	 * @param edges 
	 */
	public Board(List<Tile> tiles, List<Node> nodes, List<Edge> edges) {
		this.tiles = tiles;
		this.nodes = nodes;
		this.edges = edges;
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Tile getTile(int id) {
		for (Tile tile : tiles) {
			if (tile.getId() == id) {
				return tile;
			}
		}
		return null;
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Node getNode(int id) {
		for (Node node : nodes) {
			if (node.getId() == id) {
				return node;
			}
		}
		return null;
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Edge getEdge(int id) {
		for (Edge edge : edges) {
			if (edge.getId() == id) {
				return edge;
			}
		}
		return null;
	}

	/**
	 * 
	 * @param node 
	 * @param player 
	 * @return 
	 */
	public boolean isValidSettlementPlacement(Node node, Player player) {
		// To be implemented
		return false;
	}

	/**
	 * 
	 * @param edge 
	 * @param player 
	 * @return 
	 */
	public boolean isValidRoadPlacement(Edge edge, Player player) {
		// To be implemented
		return false;
	}

	/**
	 * 
	 * @param node 
	 * @param player 
	 * @return 
	 */
	public boolean isValidCityPlacement(Node node, Player player) {
		// To be implemented
		return false;
	}

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	public List<Node> getAdjacentNodes(Node node) {
		// To be implemented
		return new ArrayList<>();
	}

	/**
	 * 
	 * @param node 
	 * @param player 
	 * @return 
	 */
	public boolean hasAdjacentStructures(Node node, Player player) {
		// To be implemented
		return false;
	}

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	public List<Edge> getAdjacentEdges(Node node) {
		// To be implemented
		return new ArrayList<>();
	}
}