// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class City extends Structure {
	/**
	 * 
	 * @param owner 
	 * @param location 
	 */
	public City(Player owner, Node location) {
		super(owner, location);
	}

	/**
	 * 
	 * @return 
	 */
	@Override
	public int getVictoryPoints() {
		return 2;
	}
}