// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * A city placed on a node (upgrade from Settlement), worth 2 victory points.
 */
public class City extends Structure {

    public City(Player owner, Node location) {
        super(owner, location);
    }

    @Override
    public int getVictoryPoints() {
        return 2;
    }
}
