// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 * An edge on the board connecting two nodes, where roads can be placed.
 */
public class Edge {

    private int id;
    private List<Node> nodes;
    private Road road;    // 0..1 per UML

    public Edge(int id) {
        this.id = id;
        this.nodes = new ArrayList<>();
        this.road = null;
    }

    public int getId() {
        return id;
    }

    /**
     * Add a node to this edge. An edge connects at most 2 nodes.
     */
    public void addNode(Node node) {
        if (nodes.size() < 2) {
            nodes.add(node);
        }
    }

    public List<Node> getNodes() {
        return nodes;
    }

    public Road getRoad() {
        return road;
    }

    public void setRoad(Road road) {
        this.road = road;
    }
}
