// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.List;
import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private List<Node> nodes;

	/**
	 * 
	 * @param id 
	 */
	public Edge(int id) {
		this.id = id;
		this.nodes = new ArrayList<>();
	}

	/**
	 * 
	 * @return 
	 */
	public int getId() {
		return id;
	}

	/**
	 * 
	 * @return 
	 */
	public List<Node> getNodes() {
		return nodes;
	}

	/**
	 * 
	 * @param node 
	 */
	public void addNode(Node node) {
		if (nodes.size() < 2) {
			nodes.add(node);
		}
	}
}