// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.List;
import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private List<Player> players;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private int currentRound;
	/**
	 * 
	 */
	private Configuration configuration;
	/**
	 * 
	 */
	private List<Agent> agents;
	/**
	 * 
	 */
	private ResourceBank resourceBank;

	/**
	 * 
	 * @param board 
	 * @param players 
	 */
	public Game(Board board, List<Player> players) {
		this.board = board;
		this.players = players;
		this.currentRound = 0;
		this.configuration = new Configuration();
		this.resourceBank = new ResourceBank();
		this.agents = new ArrayList<>();
		
		// Create agents for each player
		for (Player player : players) {
			agents.add(new Agent(player));
		}
	}

	/**
	 * 
	 * @return 
	 */
	public int getRound() {
		return currentRound;
	}

	/**
	 * 
	 * @return 
	 */
	public void playRound() {
		currentRound++;
		
		// Each agent takes a turn
		for (Agent agent : agents) {
			agent.takeTurn(board, resourceBank);
		}
		
		printRoundSummary();
	}

	/**
	 * 
	 * @return 
	 */
	public boolean checkTermination() {
		// Check if max rounds reached
		if (currentRound >= configuration.getMaxRounds()) {
			return true;
		}
		
		// Check if any player has 10 victory points
		for (Player player : players) {
			if (player.getVictoryPoints() >= 10) {
				return true;
			}
		}
		
		return false;
	}

	/**
	 * 
	 * @return 
	 */
	public Player getWinner() {
		Player winner = null;
		int maxVP = 0;
		
		for (Player player : players) {
			if (player.getVictoryPoints() > maxVP) {
				maxVP = player.getVictoryPoints();
				winner = player;
			}
		}
		
		return winner;
	}

	/**
	 * 
	 * @return 
	 */
	public void startGame() {
		currentRound = 0;
		
		while (!checkTermination()) {
			playRound();
		}
		
		Player winner = getWinner();
		if (winner != null) {
			System.out.println("Game Over! Winner: Player " + winner.getId() + 
				" with " + winner.getVictoryPoints() + " victory points");
		}
	}

	/**
	 * 
	 * @return 
	 */
	public void printRoundSummary() {
		System.out.println("=== Round " + currentRound + " Summary ===");
		for (Player player : players) {
			System.out.println("Player " + player.getId() + ": " + 
				player.getVictoryPoints() + " VP");
		}
		System.out.println();
	}

	/**
	 * 
	 * @return 
	 */
	public ResourceBank getResourceBank() {
		return resourceBank;
	}

	/**
	 * 
	 * @param configuration 
	 */
	public void setConfiguration(Configuration configuration) {
		this.configuration = configuration;
	}

	/**
	 * 
	 * @return 
	 */
	public Board getBoard() {
		return board;
	}

	/**
	 * 
	 * @return 
	 */
	public List<Player> getPlayers() {
		return players;
	}
}