// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.Scanner;

/************************************************************/
/**
 * A human-controlled agent that reads commands from the console.
 * Implements IAgent directly (does NOT extend Agent) per UML.
 *
 * Turn flow:  waitForGo() → roll → parse commands → return Action.
 */
public class HumanAgent implements IAgent {

    private Scanner scanner;
    private CommandParser parser;
    private Player player;

    public HumanAgent(Player player) {
        this.player = player;
        this.scanner = new Scanner(System.in);
        this.parser = new CommandParser();
    }

    /**
     * Allows injection of a Scanner for testing.
     */
    public HumanAgent(Player player, Scanner scanner) {
        this.player = player;
        this.scanner = scanner;
        this.parser = new CommandParser();
    }

    public Player getPlayer() {
        return player;
    }

    /**
     * Turn automaton for human player:
     *   1. Display prompt
     *   2. Read and parse command
     *   3. Return the resulting Action
     */
    @Override
    public Action takeTurn(int roundNumber, Board board, ResourceBank resourceBank) {
        System.out.println("\n=== Player " + player.getId() + "'s turn (Round " + roundNumber + ") ===");
        System.out.println("Your resources: " + player.getResourceHand().getResources());
        System.out.println("Commands: roll, list, build settlement <id>, build city <id>, build road <from> <to>");

        while (true) {
            System.out.print("> ");
            if (!scanner.hasNextLine()) {
                // EOF — pass
                return new Action(roundNumber, player.getId(), "PASS", ActionType.PASS);
            }
            String input = scanner.nextLine().trim();

            if (input.isEmpty()) {
                continue;
            }

            Action action = parser.parse(input);
            if (action != null) {
                // Fill in the round and player info
                return new Action(roundNumber, player.getId(), action.getDescription(), action.getActionType());
            } else {
                System.out.println("Invalid command. Try: roll, list, build settlement <id>, build city <id>, build road <from> <to>");
            }
        }
    }

    /**
     * Step-forward control: blocks until the user types "go".
     * This is NOT a gameplay action — it is flow control for the simulator.
     */
    public void waitForGo() {
        System.out.println("Type 'go' to proceed to the next step.");
        while (true) {
            System.out.print(">> ");
            if (!scanner.hasNextLine()) {
                return;
            }
            String input = scanner.nextLine().trim();
            if (input.equalsIgnoreCase("go")) {
                return;
            }
            System.out.println("Type 'go' to continue.");
        }
    }
}
