// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * Interface for all agents (machine or human) that can take turns.
 */
public interface IAgent {

    /**
     * Take a turn in the game.
     *
     * @param roundNumber   the current round number
     * @param board         the game board
     * @param resourceBank  the shared resource bank
     * @return the Action chosen during this turn
     */
    Action takeTurn(int roundNumber, Board board, ResourceBank resourceBank);
}
