// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * A node (intersection) on the board where structures can be placed.
 */
public class Node {

    private int id;
    private Structure structure;   // 0..1 per UML

    public Node(int id) {
        this.id = id;
        this.structure = null;
    }

    public int getId() {
        return id;
    }

    public Structure getStructure() {
        return structure;
    }

    public void setStructure(Structure structure) {
        this.structure = structure;
    }
}
