// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private Structure structure;
	/**
	 * 
	 */
	private int id;

	/**
	 * 
	 * @param id 
	 */
	public Node(int id) {
		this.id = id;
		this.structure = null;
	}

	/**
	 * 
	 * @return 
	 */
	public int getId() {
		return id;
	}

	/**
	 * 
	 * @return 
	 */
	public Structure getStructure() {
		return structure;
	}

	/**
	 * 
	 * @param structure 
	 */
	public void setStructure(Structure structure) {
		this.structure = structure;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean hasStructure() {
		return structure != null;
	}
}