// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.List;
import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private int victoryPoints;
	/**
	 * 
	 */
	private ResourceHand resourceHand;
	/**
	 * 
	 */
	private List<Structure> structures;
	/**
	 * 
	 */
	private List<Road> roads;

	/**
	 * 
	 * @param id 
	 */
	public Player(int id) {
		this.id = id;
		this.victoryPoints = 0;
		this.resourceHand = new ResourceHand();
		this.structures = new ArrayList<>();
		this.roads = new ArrayList<>();
	}

	/**
	 * 
	 * @return 
	 */
	public int getId() {
		return id;
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
		return victoryPoints;
	}

	/**
	 * 
	 * @param delta 
	 */
	public void addVictoryPoints(int delta) {
		this.victoryPoints += delta;
	}

	/**
	 * 
	 * @return 
	 */
	public ResourceHand getResourceHand() {
		return resourceHand;
	}

	/**
	 * 
	 * @param structure 
	 */
	public void addStructure(Structure structure) {
		structures.add(structure);
		victoryPoints += structure.getVictoryPoints();
	}

	/**
	 * 
	 * @return 
	 */
	public List<Structure> getStructures() {
		return structures;
	}

	/**
	 * 
	 * @param road 
	 */
	public void addRoad(Road road) {
		roads.add(road);
	}

	/**
	 * 
	 * @return 
	 */
	public List<Road> getRoads() {
		return roads;
	}

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	public boolean buildSettlement(Node node) {
		// To be implemented
		return false;
	}

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	public boolean buildCity(Node node) {
		// To be implemented
		return false;
	}

	/**
	 * 
	 * @param edge 
	 * @return 
	 */
	public boolean buildRoad(Edge edge) {
		// To be implemented
		return false;
	}

	/**
	 * 
	 * @param diceRoll 
	 * @param board 
	 */
	public void collectResources(int diceRoll, Board board) {
		// To be implemented
	}

	/**
	 * 
	 * @param diceRoll 
	 */
	public void takeTurn(int diceRoll) {
		// To be implemented
	}

	/**
	 * 
	 * @return 
	 */
	public boolean needsToSpendCards() {
		return resourceHand.getTotalCards() > 7;
	}

	/**
	 * 
	 */
	public void tryRandomBuild() {
		// To be implemented
	}
}
