// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.HashMap;
import java.util.Map;

/************************************************************/
/**
 * 
 */
public class ResourceHand {
	/**
	 * 
	 */
	private Map<ResourceType, Integer> resources;

	/**
	 * 
	 */
	public ResourceHand() {
		resources = new HashMap<>();
		// Initialize with 0 of each resource type
		resources.put(ResourceType.BRICK, 0);
		resources.put(ResourceType.LUMBER, 0);
		resources.put(ResourceType.WOOL, 0);
		resources.put(ResourceType.GRAIN, 0);
		resources.put(ResourceType.ORE, 0);
	}

	/**
	 * 
	 * @return 
	 */
	public int getBrick() {
		return resources.get(ResourceType.BRICK);
	}

	/**
	 * 
	 * @return 
	 */
	public int getLumber() {
		return resources.get(ResourceType.LUMBER);
	}

	/**
	 * 
	 * @return 
	 */
	public int getWool() {
		return resources.get(ResourceType.WOOL);
	}

	/**
	 * 
	 * @return 
	 */
	public int getGrain() {
		return resources.get(ResourceType.GRAIN);
	}

	/**
	 * 
	 * @return 
	 */
	public int getOre() {
		return resources.get(ResourceType.ORE);
	}

	/**
	 * 
	 * @return 
	 */
	public int getTotalCards() {
		int total = 0;
		for (Integer count : resources.values()) {
			total += count;
		}
		return total;
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 * @return 
	 */
	public void add(ResourceType type, int amount) {
		Integer current = resources.get(type);
		if (current != null) {
			resources.put(type, current + amount);
		}
	}

	/**
	 * 
	 * @param type 
	 * @return 
	 */
	public int getAmount(ResourceType type) {
		Integer amount = resources.get(type);
		return amount != null ? amount : 0;
	}

	/**
	 * 
	 * @param cost 
	 * @return 
	 */
	public boolean canAfford(Map<ResourceType, Integer> cost) {
		for (Map.Entry<ResourceType, Integer> entry : cost.entrySet()) {
			if (getAmount(entry.getKey()) < entry.getValue()) {
				return false;
			}
		}
		return true;
	}

	/**
	 * 
	 * @param cost 
	 * @return 
	 */
	public boolean spend(Map<ResourceType, Integer> cost) {
		if (!canAfford(cost)) {
			return false;
		}
		
		for (Map.Entry<ResourceType, Integer> entry : cost.entrySet()) {
			ResourceType type = entry.getKey();
			Integer amount = entry.getValue();
			resources.put(type, resources.get(type) - amount);
		}
		
		return true;
	}
}