// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

import java.util.HashMap;
import java.util.Map;

/************************************************************/
/**
 * 
 */
public class ResourceBank {
	/**
	 * 
	 */
	private Map<ResourceType, Integer> availableResources;

	/**
	 * 
	 */
	public ResourceBank() {
		availableResources = new HashMap<>();
		// Initialize with 19 of each resource type
		availableResources.put(ResourceType.BRICK, 19);
		availableResources.put(ResourceType.LUMBER, 19);
		availableResources.put(ResourceType.WOOL, 19);
		availableResources.put(ResourceType.GRAIN, 19);
		availableResources.put(ResourceType.ORE, 19);
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 * @return 
	 */
	public boolean hasResource(ResourceType type, int amount) {
		Integer available = availableResources.get(type);
		return available != null && available >= amount;
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 * @return 
	 */
	public boolean takeResource(ResourceType type, int amount) {
		if (hasResource(type, amount)) {
			availableResources.put(type, availableResources.get(type) - amount);
			return true;
		}
		return false;
	}

	/**
	 * 
	 * @param type 
	 * @return 
	 */
	public int getRemainingCount(ResourceType type) {
		Integer count = availableResources.get(type);
		return count != null ? count : 0;
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 * @return 
	 */
	public void returnResource(ResourceType type, int amount) {
		Integer current = availableResources.get(type);
		if (current != null) {
			availableResources.put(type, current + amount);
		}
	}
}