// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * A road placed on an edge, owned by a player.
 */
public class Road {

    private Edge edge;
    private Player owner;

    public Road(Player owner, Edge edge) {
        this.owner = owner;
        this.edge = edge;
    }

    public Edge getEdge() {
        return edge;
    }

    public Player getOwner() {
        return owner;
    }
}
