// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	private Edge edge;
	/**
	 * 
	 */
	private Player owner;

	/**
	 * 
	 * @param owner 
	 * @param edge 
	 */
	public Road(Player owner, Edge edge) {
		this.owner = owner;
		this.edge = edge;
	}

	/**
	 * 
	 * @return 
	 */
	public Edge getEdge() {
		return edge;
	}

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
		return owner;
	}
}