// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * The robber piece. Moves to a tile when a 7 is rolled.
 */
public class Robber {

    private Tile location;

    public Robber() {
        this.location = null;
    }

    public void move(Tile tile) {
        this.location = tile;
    }

    public Tile getLocation() {
        return location;
    }
}
