// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * A settlement placed on a node, worth 1 victory point.
 */
public class Settlement extends Structure {

    public Settlement(Player owner, Node location) {
        super(owner, location);
    }

    @Override
    public int getVictoryPoints() {
        return 1;
    }
}
