// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * Abstract base for structures placed on nodes (Settlement, City).
 */
public abstract class Structure {

    private Player owner;
    private Node location;

    protected Structure(Player owner, Node location) {
        this.owner = owner;
        this.location = location;
    }

    public Player getOwner() {
        return owner;
    }

    public abstract int getVictoryPoints();

    public Node getLocation() {
        return location;
    }
}
