// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public abstract class Structure {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Node location;

	/**
	 * 
	 * @param owner 
	 * @param location 
	 */
	public Structure(Player owner, Node location) {
		this.owner = owner;
		this.location = location;
	}

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
		return owner;
	}

	/**
	 * 
	 * @return 
	 */
	public abstract int getVictoryPoints();

	/**
	 * 
	 * @return 
	 */
	public Node getLocation() {
		return location;
	}
}