// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * A hex tile on the board with a resource type and dice number.
 */
public class Tile {

    private int id;
    private ResourceType resourceType;
    private int number;

    public Tile(int id, ResourceType resourceType, int number) {
        this.id = id;
        this.resourceType = resourceType;
        this.number = number;
    }

    public int getId() {
        return id;
    }

    public ResourceType getResourceType() {
        return resourceType;
    }

    public int getNumber() {
        return number;
    }
}
