// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private ResourceType resourceType;
	/**
	 * 
	 */
	private int number;

	/**
	 * 
	 * @param id 
	 * @param resourceType 
	 * @param number 
	 */
	public Tile(int id, ResourceType resourceType, int number) {
		this.id = id;
		this.resourceType = resourceType;
		this.number = number;
	}

	/**
	 * 
	 * @return 
	 */
	public int getId() {
		return id;
	}

	/**
	 * 
	 * @return 
	 */
	public ResourceType getResourceType() {
		return resourceType;
	}

	/**
	 * 
	 * @return 
	 */
	public int getNumber() {
		return number;
	}
}