// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * Represents a trade offer between players.
 */
public class TradeOffer {

    private ResourceHand offeredResources;
    private ResourceHand requestedResources;

    public TradeOffer(ResourceHand offered, ResourceHand requested) {
        this.offeredResources = offered;
        this.requestedResources = requested;
    }

    public ResourceHand getOfferedResources() {
        return offeredResources;
    }

    public ResourceHand getRequestedResources() {
        return requestedResources;
    }

    public void accept() {
        // Accept logic: transfer resources between players
    }

    public void reject() {
        // Reject logic: no resource transfer
    }
}
